config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :usuarios
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
   def index
      @usuarios=Usuario.all
    end

  def show
      @usuarios=Usuario.find(params[:id])
      render action: "detalle"
    end

  def detalle
      @usuarios=Usuario.find(1)
    end

  def destroy
      Usuario.find(params[:id]).destroy
      redirect_to usuarios_url
    end

  def edit
      @usuarios=Usuario.find(params[:id])
    end

  def update
      @usuarios=Usuario.find(params[:id])
      if @usuarios.update_attributes(usuarios_params)
        redirect_to usuarios_url
      else
        render action: 'edit'
      end
    end
  def new
      @usuarios=Usuario.new
    end
  def create
      @usuarios=Usuario.new(usuarios_params)
      if @usuarios.save
        redirect_to usuarios_url
      else
        render action: 'new'
      end
    end
  end

  private
  def usuarios_params
    params.require(:usuario).permit(:nombre,:email)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogprueba - Diego Narvaez</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/detalle.html.erb
<h1>
segunda pagina de Diego Narvaez - Detalle de Usuario
</h1>
<table>
  <tr>
    <td>Id:</td>
    <td><%= @usuarios.id %></td>
  </tr>
   <tr>
    <td>Nombre:</td>
    <td><%= @usuarios.nombre %></td>
  </tr>
   <tr>
    <td>Email:</td>
    <td><%= @usuarios.email %></td>
  </tr>
   <tr>
    <td>Fecha Creación</td>
    <td><%= @usuarios.created_at %></td>
  </tr>
   <tr>
    <td>Ultima Actualización</td>
    <td><%= @usuarios.updated_at %></td>
  </tr>
</table>
<br>
<h3><%= link_to 'Atras', usuarios_path %></h3>

app/views/usuarios/edit.html.erb
<h1>
Tercera pagina de Diego Narvaez - Edit
</h1>
<h2>
Editando Usuarios
</h2>
<%= form_for(@usuarios) do |f| %>

<div class="field">
  <%= f.label :nombre %><br>
  <%= f.text_field :nombre %>
</div>
<div class="field">
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</div>
<div class="actions">
  <%= f.submit 'Guardar Cambios' %>
</div>
<% end %>

<h3><%= link_to 'Atras', usuarios_path %></h3>

app/views/usuarios/index.html.erb
<h1>primera pagina de Diego Narvaez </h1>
<h1>Listando Usuarios </h1>
<table>
  <tr>
    <td>Nombre</td>
    <td>Email</td>
  </tr>

  <% @usuarios.each do |usuario| %>
    <tr>
      <td><%= link_to usuario.nombre, usuario %></td>
      <td><%= usuario.email %></td>
      <td><%= link_to "Editar", edit_usuario_path(usuario) %></td>
      <td><%= link_to "Eliminar", usuario, method: :delete, confirm: "Estas Seguro" %></td>
    </tr>
  <% end %>
  <% if @usuarios.size==0 %>
    <tr>
    <td>Usuarios No Encontrados</td>
    <td></td>
  </tr>
  <% end %>
</table>
<br>
<br>
<%= link_to "Nuevo Usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>
Cuarta pagina de Diego Narvaez - New
</h1>
<h2>
Nuevo Usuario
</h2>
<%= form_for(@usuarios) do |f| %>

<div class="field">
  <%= f.label :nombre %>
  <%= f.text_field :nombre %>
</div>
<div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>
<div class="actions">
  <%= f.submit 'Guardar' %>
</div>
<% end %>

<h3><%= link_to 'Atras', usuarios_path %></h3>

app/views/usuarios/show.html.erb
<h1>
segunda pagina de Diego Narvaez
</h1>